import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export interface Country {
  code: string
  name: string
  flag?: string // emoji fallback (kept for compatibility; UI uses flagUrl)
  flagUrl?: string // real flag image (flagcdn) — used for actual countries
}

// Every recognised country/territory in the world. `code` is the ISO 3166-1
// alpha-2 code used to build the flagcdn image URL. Companies/schools pick from
// this list (or type their own), and students can filter jobs by any of these.
export const COUNTRIES: Country[] = [
  { code: 'all', name: 'All countries', flag: '🌍' },
  { code: 'remote', name: 'Remote', flag: '🛰️' },
  { code: 'af', name: 'Afghanistan', flagUrl: 'https://flagcdn.com/w40/af.png' },
  { code: 'al', name: 'Albania', flagUrl: 'https://flagcdn.com/w40/al.png' },
  { code: 'dz', name: 'Algeria', flagUrl: 'https://flagcdn.com/w40/dz.png' },
  { code: 'ad', name: 'Andorra', flagUrl: 'https://flagcdn.com/w40/ad.png' },
  { code: 'ao', name: 'Angola', flagUrl: 'https://flagcdn.com/w40/ao.png' },
  { code: 'ag', name: 'Antigua and Barbuda', flagUrl: 'https://flagcdn.com/w40/ag.png' },
  { code: 'ar', name: 'Argentina', flagUrl: 'https://flagcdn.com/w40/ar.png' },
  { code: 'am', name: 'Armenia', flagUrl: 'https://flagcdn.com/w40/am.png' },
  { code: 'au', name: 'Australia', flagUrl: 'https://flagcdn.com/w40/au.png' },
  { code: 'at', name: 'Austria', flagUrl: 'https://flagcdn.com/w40/at.png' },
  { code: 'az', name: 'Azerbaijan', flagUrl: 'https://flagcdn.com/w40/az.png' },
  { code: 'bs', name: 'Bahamas', flagUrl: 'https://flagcdn.com/w40/bs.png' },
  { code: 'bh', name: 'Bahrain', flagUrl: 'https://flagcdn.com/w40/bh.png' },
  { code: 'bd', name: 'Bangladesh', flagUrl: 'https://flagcdn.com/w40/bd.png' },
  { code: 'bb', name: 'Barbados', flagUrl: 'https://flagcdn.com/w40/bb.png' },
  { code: 'by', name: 'Belarus', flagUrl: 'https://flagcdn.com/w40/by.png' },
  { code: 'be', name: 'Belgium', flagUrl: 'https://flagcdn.com/w40/be.png' },
  { code: 'bz', name: 'Belize', flagUrl: 'https://flagcdn.com/w40/bz.png' },
  { code: 'bj', name: 'Benin', flagUrl: 'https://flagcdn.com/w40/bj.png' },
  { code: 'bt', name: 'Bhutan', flagUrl: 'https://flagcdn.com/w40/bt.png' },
  { code: 'bo', name: 'Bolivia', flagUrl: 'https://flagcdn.com/w40/bo.png' },
  { code: 'ba', name: 'Bosnia and Herzegovina', flagUrl: 'https://flagcdn.com/w40/ba.png' },
  { code: 'bw', name: 'Botswana', flagUrl: 'https://flagcdn.com/w40/bw.png' },
  { code: 'br', name: 'Brazil', flagUrl: 'https://flagcdn.com/w40/br.png' },
  { code: 'bn', name: 'Brunei', flagUrl: 'https://flagcdn.com/w40/bn.png' },
  { code: 'bg', name: 'Bulgaria', flagUrl: 'https://flagcdn.com/w40/bg.png' },
  { code: 'bf', name: 'Burkina Faso', flagUrl: 'https://flagcdn.com/w40/bf.png' },
  { code: 'bi', name: 'Burundi', flagUrl: 'https://flagcdn.com/w40/bi.png' },
  { code: 'cv', name: 'Cabo Verde', flagUrl: 'https://flagcdn.com/w40/cv.png' },
  { code: 'kh', name: 'Cambodia', flagUrl: 'https://flagcdn.com/w40/kh.png' },
  { code: 'cm', name: 'Cameroon', flagUrl: 'https://flagcdn.com/w40/cm.png' },
  { code: 'ca', name: 'Canada', flagUrl: 'https://flagcdn.com/w40/ca.png' },
  { code: 'cf', name: 'Central African Republic', flagUrl: 'https://flagcdn.com/w40/cf.png' },
  { code: 'td', name: 'Chad', flagUrl: 'https://flagcdn.com/w40/td.png' },
  { code: 'cl', name: 'Chile', flagUrl: 'https://flagcdn.com/w40/cl.png' },
  { code: 'cn', name: 'China', flagUrl: 'https://flagcdn.com/w40/cn.png' },
  { code: 'co', name: 'Colombia', flagUrl: 'https://flagcdn.com/w40/co.png' },
  { code: 'km', name: 'Comoros', flagUrl: 'https://flagcdn.com/w40/km.png' },
  { code: 'cg', name: 'Congo', flagUrl: 'https://flagcdn.com/w40/cg.png' },
  { code: 'cd', name: 'Congo, Democratic Republic of the', flagUrl: 'https://flagcdn.com/w40/cd.png' },
  { code: 'cr', name: 'Costa Rica', flagUrl: 'https://flagcdn.com/w40/cr.png' },
  { code: 'ci', name: "Côte d'Ivoire", flagUrl: 'https://flagcdn.com/w40/ci.png' },
  { code: 'hr', name: 'Croatia', flagUrl: 'https://flagcdn.com/w40/hr.png' },
  { code: 'cu', name: 'Cuba', flagUrl: 'https://flagcdn.com/w40/cu.png' },
  { code: 'cy', name: 'Cyprus', flagUrl: 'https://flagcdn.com/w40/cy.png' },
  { code: 'cz', name: 'Czechia', flagUrl: 'https://flagcdn.com/w40/cz.png' },
  { code: 'dk', name: 'Denmark', flagUrl: 'https://flagcdn.com/w40/dk.png' },
  { code: 'dj', name: 'Djibouti', flagUrl: 'https://flagcdn.com/w40/dj.png' },
  { code: 'dm', name: 'Dominica', flagUrl: 'https://flagcdn.com/w40/dm.png' },
  { code: 'do', name: 'Dominican Republic', flagUrl: 'https://flagcdn.com/w40/do.png' },
  { code: 'ec', name: 'Ecuador', flagUrl: 'https://flagcdn.com/w40/ec.png' },
  { code: 'eg', name: 'Egypt', flagUrl: 'https://flagcdn.com/w40/eg.png' },
  { code: 'sv', name: 'El Salvador', flagUrl: 'https://flagcdn.com/w40/sv.png' },
  { code: 'gq', name: 'Equatorial Guinea', flagUrl: 'https://flagcdn.com/w40/gq.png' },
  { code: 'er', name: 'Eritrea', flagUrl: 'https://flagcdn.com/w40/er.png' },
  { code: 'ee', name: 'Estonia', flagUrl: 'https://flagcdn.com/w40/ee.png' },
  { code: 'sz', name: 'Eswatini', flagUrl: 'https://flagcdn.com/w40/sz.png' },
  { code: 'et', name: 'Ethiopia', flagUrl: 'https://flagcdn.com/w40/et.png' },
  { code: 'fj', name: 'Fiji', flagUrl: 'https://flagcdn.com/w40/fj.png' },
  { code: 'fi', name: 'Finland', flagUrl: 'https://flagcdn.com/w40/fi.png' },
  { code: 'fr', name: 'France', flagUrl: 'https://flagcdn.com/w40/fr.png' },
  { code: 'ga', name: 'Gabon', flagUrl: 'https://flagcdn.com/w40/ga.png' },
  { code: 'gm', name: 'Gambia', flagUrl: 'https://flagcdn.com/w40/gm.png' },
  { code: 'ge', name: 'Georgia', flagUrl: 'https://flagcdn.com/w40/ge.png' },
  { code: 'de', name: 'Germany', flagUrl: 'https://flagcdn.com/w40/de.png' },
  { code: 'gh', name: 'Ghana', flagUrl: 'https://flagcdn.com/w40/gh.png' },
  { code: 'gr', name: 'Greece', flagUrl: 'https://flagcdn.com/w40/gr.png' },
  { code: 'gt', name: 'Guatemala', flagUrl: 'https://flagcdn.com/w40/gt.png' },
  { code: 'gn', name: 'Guinea', flagUrl: 'https://flagcdn.com/w40/gn.png' },
  { code: 'gw', name: 'Guinea-Bissau', flagUrl: 'https://flagcdn.com/w40/gw.png' },
  { code: 'gy', name: 'Guyana', flagUrl: 'https://flagcdn.com/w40/gy.png' },
  { code: 'ht', name: 'Haiti', flagUrl: 'https://flagcdn.com/w40/ht.png' },
  { code: 'hn', name: 'Honduras', flagUrl: 'https://flagcdn.com/w40/hn.png' },
  { code: 'hk', name: 'Hong Kong', flagUrl: 'https://flagcdn.com/w40/hk.png' },
  { code: 'hu', name: 'Hungary', flagUrl: 'https://flagcdn.com/w40/hu.png' },
  { code: 'is', name: 'Iceland', flagUrl: 'https://flagcdn.com/w40/is.png' },
  { code: 'in', name: 'India', flagUrl: 'https://flagcdn.com/w40/in.png' },
  { code: 'id', name: 'Indonesia', flagUrl: 'https://flagcdn.com/w40/id.png' },
  { code: 'ir', name: 'Iran', flagUrl: 'https://flagcdn.com/w40/ir.png' },
  { code: 'iq', name: 'Iraq', flagUrl: 'https://flagcdn.com/w40/iq.png' },
  { code: 'ie', name: 'Ireland', flagUrl: 'https://flagcdn.com/w40/ie.png' },
  { code: 'il', name: 'Israel', flagUrl: 'https://flagcdn.com/w40/il.png' },
  { code: 'it', name: 'Italy', flagUrl: 'https://flagcdn.com/w40/it.png' },
  { code: 'jm', name: 'Jamaica', flagUrl: 'https://flagcdn.com/w40/jm.png' },
  { code: 'jp', name: 'Japan', flagUrl: 'https://flagcdn.com/w40/jp.png' },
  { code: 'jo', name: 'Jordan', flagUrl: 'https://flagcdn.com/w40/jo.png' },
  { code: 'kz', name: 'Kazakhstan', flagUrl: 'https://flagcdn.com/w40/kz.png' },
  { code: 'ke', name: 'Kenya', flagUrl: 'https://flagcdn.com/w40/ke.png' },
  { code: 'ki', name: 'Kiribati', flagUrl: 'https://flagcdn.com/w40/ki.png' },
  { code: 'kp', name: 'Korea, North', flagUrl: 'https://flagcdn.com/w40/kp.png' },
  { code: 'kr', name: 'Korea, South', flagUrl: 'https://flagcdn.com/w40/kr.png' },
  { code: 'kw', name: 'Kuwait', flagUrl: 'https://flagcdn.com/w40/kw.png' },
  { code: 'kg', name: 'Kyrgyzstan', flagUrl: 'https://flagcdn.com/w40/kg.png' },
  { code: 'la', name: "Laos", flagUrl: 'https://flagcdn.com/w40/la.png' },
  { code: 'lv', name: 'Latvia', flagUrl: 'https://flagcdn.com/w40/lv.png' },
  { code: 'lb', name: 'Lebanon', flagUrl: 'https://flagcdn.com/w40/lb.png' },
  { code: 'ls', name: 'Lesotho', flagUrl: 'https://flagcdn.com/w40/ls.png' },
  { code: 'lr', name: 'Liberia', flagUrl: 'https://flagcdn.com/w40/lr.png' },
  { code: 'ly', name: 'Libya', flagUrl: 'https://flagcdn.com/w40/ly.png' },
  { code: 'li', name: 'Liechtenstein', flagUrl: 'https://flagcdn.com/w40/li.png' },
  { code: 'lt', name: 'Lithuania', flagUrl: 'https://flagcdn.com/w40/lt.png' },
  { code: 'lu', name: 'Luxembourg', flagUrl: 'https://flagcdn.com/w40/lu.png' },
  { code: 'mg', name: 'Madagascar', flagUrl: 'https://flagcdn.com/w40/mg.png' },
  { code: 'mw', name: 'Malawi', flagUrl: 'https://flagcdn.com/w40/mw.png' },
  { code: 'my', name: 'Malaysia', flagUrl: 'https://flagcdn.com/w40/my.png' },
  { code: 'mv', name: 'Maldives', flagUrl: 'https://flagcdn.com/w40/mv.png' },
  { code: 'ml', name: 'Mali', flagUrl: 'https://flagcdn.com/w40/ml.png' },
  { code: 'mt', name: 'Malta', flagUrl: 'https://flagcdn.com/w40/mt.png' },
  { code: 'mh', name: 'Marshall Islands', flagUrl: 'https://flagcdn.com/w40/mh.png' },
  { code: 'mr', name: 'Mauritania', flagUrl: 'https://flagcdn.com/w40/mr.png' },
  { code: 'mu', name: 'Mauritius', flagUrl: 'https://flagcdn.com/w40/mu.png' },
  { code: 'mx', name: 'Mexico', flagUrl: 'https://flagcdn.com/w40/mx.png' },
  { code: 'fm', name: 'Micronesia', flagUrl: 'https://flagcdn.com/w40/fm.png' },
  { code: 'md', name: 'Moldova', flagUrl: 'https://flagcdn.com/w40/md.png' },
  { code: 'mc', name: 'Monaco', flagUrl: 'https://flagcdn.com/w40/mc.png' },
  { code: 'mn', name: 'Mongolia', flagUrl: 'https://flagcdn.com/w40/mn.png' },
  { code: 'me', name: 'Montenegro', flagUrl: 'https://flagcdn.com/w40/me.png' },
  { code: 'ma', name: 'Morocco', flagUrl: 'https://flagcdn.com/w40/ma.png' },
  { code: 'mz', name: 'Mozambique', flagUrl: 'https://flagcdn.com/w40/mz.png' },
  { code: 'mm', name: 'Myanmar', flagUrl: 'https://flagcdn.com/w40/mm.png' },
  { code: 'na', name: 'Namibia', flagUrl: 'https://flagcdn.com/w40/na.png' },
  { code: 'nr', name: 'Nauru', flagUrl: 'https://flagcdn.com/w40/nr.png' },
  { code: 'np', name: 'Nepal', flagUrl: 'https://flagcdn.com/w40/np.png' },
  { code: 'nl', name: 'Netherlands', flagUrl: 'https://flagcdn.com/w40/nl.png' },
  { code: 'nz', name: 'New Zealand', flagUrl: 'https://flagcdn.com/w40/nz.png' },
  { code: 'ni', name: 'Nicaragua', flagUrl: 'https://flagcdn.com/w40/ni.png' },
  { code: 'ne', name: 'Niger', flagUrl: 'https://flagcdn.com/w40/ne.png' },
  { code: 'ng', name: 'Nigeria', flagUrl: 'https://flagcdn.com/w40/ng.png' },
  { code: 'mk', name: 'North Macedonia', flagUrl: 'https://flagcdn.com/w40/mk.png' },
  { code: 'no', name: 'Norway', flagUrl: 'https://flagcdn.com/w40/no.png' },
  { code: 'om', name: 'Oman', flagUrl: 'https://flagcdn.com/w40/om.png' },
  { code: 'pk', name: 'Pakistan', flagUrl: 'https://flagcdn.com/w40/pk.png' },
  { code: 'pw', name: 'Palau', flagUrl: 'https://flagcdn.com/w40/pw.png' },
  { code: 'pa', name: 'Panama', flagUrl: 'https://flagcdn.com/w40/pa.png' },
  { code: 'pg', name: 'Papua New Guinea', flagUrl: 'https://flagcdn.com/w40/pg.png' },
  { code: 'py', name: 'Paraguay', flagUrl: 'https://flagcdn.com/w40/py.png' },
  { code: 'pe', name: 'Peru', flagUrl: 'https://flagcdn.com/w40/pe.png' },
  { code: 'ph', name: 'Philippines', flagUrl: 'https://flagcdn.com/w40/ph.png' },
  { code: 'pl', name: 'Poland', flagUrl: 'https://flagcdn.com/w40/pl.png' },
  { code: 'pt', name: 'Portugal', flagUrl: 'https://flagcdn.com/w40/pt.png' },
  { code: 'qa', name: 'Qatar', flagUrl: 'https://flagcdn.com/w40/qa.png' },
  { code: 'ro', name: 'Romania', flagUrl: 'https://flagcdn.com/w40/ro.png' },
  { code: 'ru', name: 'Russia', flagUrl: 'https://flagcdn.com/w40/ru.png' },
  { code: 'rw', name: 'Rwanda', flagUrl: 'https://flagcdn.com/w40/rw.png' },
  { code: 'kn', name: 'Saint Kitts and Nevis', flagUrl: 'https://flagcdn.com/w40/kn.png' },
  { code: 'lc', name: 'Saint Lucia', flagUrl: 'https://flagcdn.com/w40/lc.png' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', flagUrl: 'https://flagcdn.com/w40/vc.png' },
  { code: 'ws', name: 'Samoa', flagUrl: 'https://flagcdn.com/w40/ws.png' },
  { code: 'sm', name: 'San Marino', flagUrl: 'https://flagcdn.com/w40/sm.png' },
  { code: 'st', name: 'Sao Tome and Principe', flagUrl: 'https://flagcdn.com/w40/st.png' },
  { code: 'sa', name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/w40/sa.png' },
  { code: 'sn', name: 'Senegal', flagUrl: 'https://flagcdn.com/w40/sn.png' },
  { code: 'rs', name: 'Serbia', flagUrl: 'https://flagcdn.com/w40/rs.png' },
  { code: 'sc', name: 'Seychelles', flagUrl: 'https://flagcdn.com/w40/sc.png' },
  { code: 'sl', name: 'Sierra Leone', flagUrl: 'https://flagcdn.com/w40/sl.png' },
  { code: 'sg', name: 'Singapore', flagUrl: 'https://flagcdn.com/w40/sg.png' },
  { code: 'sk', name: 'Slovakia', flagUrl: 'https://flagcdn.com/w40/sk.png' },
  { code: 'si', name: 'Slovenia', flagUrl: 'https://flagcdn.com/w40/si.png' },
  { code: 'sb', name: 'Solomon Islands', flagUrl: 'https://flagcdn.com/w40/sb.png' },
  { code: 'so', name: 'Somalia', flagUrl: 'https://flagcdn.com/w40/so.png' },
  { code: 'za', name: 'South Africa', flagUrl: 'https://flagcdn.com/w40/za.png' },
  { code: 'ss', name: 'South Sudan', flagUrl: 'https://flagcdn.com/w40/ss.png' },
  { code: 'es', name: 'Spain', flagUrl: 'https://flagcdn.com/w40/es.png' },
  { code: 'lk', name: 'Sri Lanka', flagUrl: 'https://flagcdn.com/w40/lk.png' },
  { code: 'sd', name: 'Sudan', flagUrl: 'https://flagcdn.com/w40/sd.png' },
  { code: 'sr', name: 'Suriname', flagUrl: 'https://flagcdn.com/w40/sr.png' },
  { code: 'se', name: 'Sweden', flagUrl: 'https://flagcdn.com/w40/se.png' },
  { code: 'ch', name: 'Switzerland', flagUrl: 'https://flagcdn.com/w40/ch.png' },
  { code: 'sy', name: 'Syria', flagUrl: 'https://flagcdn.com/w40/sy.png' },
  { code: 'tw', name: 'Taiwan', flagUrl: 'https://flagcdn.com/w40/tw.png' },
  { code: 'tj', name: 'Tajikistan', flagUrl: 'https://flagcdn.com/w40/tj.png' },
  { code: 'tz', name: 'Tanzania', flagUrl: 'https://flagcdn.com/w40/tz.png' },
  { code: 'th', name: 'Thailand', flagUrl: 'https://flagcdn.com/w40/th.png' },
  { code: 'tl', name: 'Timor-Leste', flagUrl: 'https://flagcdn.com/w40/tl.png' },
  { code: 'tg', name: 'Togo', flagUrl: 'https://flagcdn.com/w40/tg.png' },
  { code: 'to', name: 'Tonga', flagUrl: 'https://flagcdn.com/w40/to.png' },
  { code: 'tt', name: 'Trinidad and Tobago', flagUrl: 'https://flagcdn.com/w40/tt.png' },
  { code: 'tn', name: 'Tunisia', flagUrl: 'https://flagcdn.com/w40/tn.png' },
  { code: 'tr', name: 'Turkey', flagUrl: 'https://flagcdn.com/w40/tr.png' },
  { code: 'tm', name: 'Turkmenistan', flagUrl: 'https://flagcdn.com/w40/tm.png' },
  { code: 'tv', name: 'Tuvalu', flagUrl: 'https://flagcdn.com/w40/tv.png' },
  { code: 'ug', name: 'Uganda', flagUrl: 'https://flagcdn.com/w40/ug.png' },
  { code: 'ua', name: 'Ukraine', flagUrl: 'https://flagcdn.com/w40/ua.png' },
  { code: 'ae', name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w40/ae.png' },
  { code: 'gb', name: 'United Kingdom', flagUrl: 'https://flagcdn.com/w40/gb.png' },
  { code: 'us', name: 'United States', flagUrl: 'https://flagcdn.com/w40/us.png' },
  { code: 'uy', name: 'Uruguay', flagUrl: 'https://flagcdn.com/w40/uy.png' },
  { code: 'uz', name: 'Uzbekistan', flagUrl: 'https://flagcdn.com/w40/uz.png' },
  { code: 'vu', name: 'Vanuatu', flagUrl: 'https://flagcdn.com/w40/vu.png' },
  { code: 've', name: 'Venezuela', flagUrl: 'https://flagcdn.com/w40/ve.png' },
  { code: 'vn', name: 'Vietnam', flagUrl: 'https://flagcdn.com/w40/vn.png' },
  { code: 'ye', name: 'Yemen', flagUrl: 'https://flagcdn.com/w40/ye.png' },
  { code: 'zm', name: 'Zambia', flagUrl: 'https://flagcdn.com/w40/zm.png' },
  { code: 'zw', name: 'Zimbabwe', flagUrl: 'https://flagcdn.com/w40/zw.png' },
  // Common dependent territories / special areas (kept separate from sovereign list)
  { code: 'xk', name: 'Kosovo', flagUrl: 'https://flagcdn.com/w40/xk.png' },
  { code: 'ps', name: 'Palestine', flagUrl: 'https://flagcdn.com/w40/ps.png' },
  { code: 'eh', name: 'Western Sahara', flagUrl: 'https://flagcdn.com/w40/eh.png' },
  { code: 'gl', name: 'Greenland', flagUrl: 'https://flagcdn.com/w40/gl.png' },
  { code: 'fo', name: 'Faroe Islands', flagUrl: 'https://flagcdn.com/w40/fo.png' },
  { code: 'gi', name: 'Gibraltar', flagUrl: 'https://flagcdn.com/w40/gi.png' },
  { code: 'bm', name: 'Bermuda', flagUrl: 'https://flagcdn.com/w40/bm.png' },
  { code: 'ky', name: 'Cayman Islands', flagUrl: 'https://flagcdn.com/w40/ky.png' },
  { code: 'gp', name: 'Guadeloupe', flagUrl: 'https://flagcdn.com/w40/gp.png' },
  { code: 'mq', name: 'Martinique', flagUrl: 'https://flagcdn.com/w40/mq.png' },
  { code: 're', name: 'Réunion', flagUrl: 'https://flagcdn.com/w40/re.png' },
  { code: 'nc', name: 'New Caledonia', flagUrl: 'https://flagcdn.com/w40/nc.png' },
  { code: 'pf', name: 'French Polynesia', flagUrl: 'https://flagcdn.com/w40/pf.png' },
  { code: 'aw', name: 'Aruba', flagUrl: 'https://flagcdn.com/w40/aw.png' },
  { code: 'cw', name: 'Curaçao', flagUrl: 'https://flagcdn.com/w40/cw.png' },
  { code: 'sx', name: 'Sint Maarten', flagUrl: 'https://flagcdn.com/w40/sx.png' },
  { code: 'im', name: 'Isle of Man', flagUrl: 'https://flagcdn.com/w40/im.png' },
  { code: 'je', name: 'Jersey', flagUrl: 'https://flagcdn.com/w40/je.png' },
  { code: 'gg', name: 'Guernsey', flagUrl: 'https://flagcdn.com/w40/gg.png' },
  { code: 'mo', name: 'Macao', flagUrl: 'https://flagcdn.com/w40/mo.png' },
  { code: 'pr', name: 'Puerto Rico', flagUrl: 'https://flagcdn.com/w40/pr.png' },
  { code: 'vg', name: 'British Virgin Islands', flagUrl: 'https://flagcdn.com/w40/vg.png' },
  { code: 'vi', name: 'U.S. Virgin Islands', flagUrl: 'https://flagcdn.com/w40/vi.png' },
  { code: 'yt', name: 'Mayotte', flagUrl: 'https://flagcdn.com/w40/yt.png' },
  { code: 'bl', name: 'Saint Barthélemy', flagUrl: 'https://flagcdn.com/w40/bl.png' },
  { code: 'mf', name: 'Saint Martin', flagUrl: 'https://flagcdn.com/w40/mf.png' },
]

interface GeoState {
  country: string // country name, or 'All countries'
  setCountry: (name: string) => void
}

export const useGeo = create<GeoState>()(
  persist(
    (set) => ({
      // Default to where we are now — Rwanda.
      country: 'Rwanda',
      setCountry: (name) => set({ country: name }),
    }),
    { name: 'optryva-geo-v2' }, // bumped so existing sessions pick up the Rwanda default
  ),
)

// Live per-country listing counts, published by the Jobs page so the global
// country picker can show how many roles (and how many internships) exist per
// country. Empty until the Jobs page has loaded its listings.
export interface CountryStat {
  total: number
  internships: number
}

interface CountryStatsState {
  stats: Record<string, CountryStat>
  setStats: (s: Record<string, CountryStat>) => void
}

export const useCountryStats = create<CountryStatsState>()((set) => ({
  stats: {},
  setStats: (s) => set({ stats: s }),
}))
